(deftheme blee-dark-1
  "Default on blee3. Blk Bg Green Fg +.")

(custom-theme-set-faces
 'blee-dark-1
 '(default ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "Green" :background "Black" :stipple nil :inherit nil))))
 '(cursor ((t (:background "Magenta"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "cyan"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(highlight ((t (:foreground "#1B2229" :background "darkolivegreen"))))
 '(region ((t (:extend t :background "blue3"))))
 '(shadow ((t (:foreground "grey70"))))
 '(secondary-selection ((t (:extend t :background "SkyBlue4"))))
 '(trailing-whitespace ((t (:background "red1"))))
 '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-comment-delimiter-face ((t nil)))
 '(font-lock-comment-face ((t nil)))
 '(font-lock-constant-face ((t (:foreground "Aquamarine"))))
 '(font-lock-doc-face ((t (:foreground "LightSalmon" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
 '(font-lock-keyword-face ((t nil)))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "LightSteelBlue" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :foreground "yellow" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :foreground "yellow" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "LightSalmon"))))
 '(font-lock-type-face ((t (:foreground "PaleGreen"))))
 '(font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
 '(font-lock-warning-face ((t (:foreground "Pink" :inherit (warning)))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "cyan1"))))
 '(link-visited ((t (:foreground "violet" :underline (:color foreground-color :style line)))))
 '(fringe ((t (:foreground "#3f444a" :background "grey10" :inherit (default)))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :family "Sans Serif"))))
 '(mode-line ((t (:box (:line-width (1 . -1) :color nil :style released-button) :foreground "black" :background "grey75"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#51afef"))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "grey40" :style released-button) :inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width (1 . -1) :color "grey40" :style nil) :foreground "grey80" :background "grey30"))))
 '(isearch ((t (:weight bold :foreground "brown4" :background "palevioletred2" :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#1B2229" :background "red4"))))
 '(lazy-highlight ((t (:weight bold :foreground "#DFDFDF" :background "paleturquoise4"))))
 '(match ((t (:weight bold :foreground "#98be65" :background "RoyalBlue3"))))
 '(next-error ((t (:background "blue3"))))
 '(query-replace ((t (:background "palevioletred2" :foreground "brown4")))))

(provide-theme 'blee-dark-1)
